ALTER TABLE `users` ADD `facilityID` MEDIUMINT( 8 ) UNSIGNED NOT NULL AFTER `organization_id` ,
ADD `hubID` MEDIUMINT( 8 ) UNSIGNED NOT NULL AFTER `facilityID` ,
ADD `ipID` MEDIUMINT( 8 ) UNSIGNED NOT NULL AFTER `hubID` ;